-- Culebro Abogados — Portal (MySQL / GoDaddy). Fase 2.
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','abogado','cliente') NOT NULL DEFAULT 'cliente',
  active TINYINT NOT NULL DEFAULT 1,
  twofa TINYINT NOT NULL DEFAULT 0,
  totp_secret VARCHAR(64) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Si la tabla users ya existía:
-- ALTER TABLE users ADD COLUMN twofa TINYINT NOT NULL DEFAULT 0, ADD COLUMN totp_secret VARCHAR(64) NULL;

CREATE TABLE IF NOT EXISTS audit_log (
  id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NULL,
  action VARCHAR(80) NOT NULL, ip VARCHAR(64), at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), email VARCHAR(254),
  phone VARCHAR(40), message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cases (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(200) NOT NULL, area VARCHAR(80),
  client_id INT NULL, lawyer_id INT NULL,
  status ENUM('nuevo','en_proceso','cerrado') NOT NULL DEFAULT 'nuevo',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (lawyer_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS case_updates (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL, author_id INT NULL,
  body TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ================= Fase 2.1 — Expediente de trabajo (A/B/C/D) =================
-- Columnas nuevas en cases (ejecutar una vez; MySQL 8 soporta IF NOT EXISTS).
ALTER TABLE cases
  ADD COLUMN IF NOT EXISTS matter_no VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS authority VARCHAR(160) NULL,
  ADD COLUMN IF NOT EXISTS amount DECIMAL(14,2) NULL,
  ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'MXN',
  ADD COLUMN IF NOT EXISTS risk ENUM('alto','medio','bajo') NOT NULL DEFAULT 'medio';

CREATE TABLE IF NOT EXISTS deadlines (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL,
  title VARCHAR(200) NOT NULL, due_date DATE NOT NULL,
  kind ENUM('procesal','contractual','fiscal','administrativo','otro') NOT NULL DEFAULT 'otro',
  done TINYINT NOT NULL DEFAULT 0, created_by INT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL,
  title VARCHAR(200) NOT NULL, assignee_id INT NULL, due_date DATE NULL,
  status ENUM('pendiente','en_proceso','hecha') NOT NULL DEFAULT 'pendiente',
  created_by INT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS parties (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL,
  name VARCHAR(160) NOT NULL,
  role ENUM('cliente','contraparte','tercero','representante','notario','autoridad','co-counsel','perito') NOT NULL DEFAULT 'tercero',
  org VARCHAR(160) NULL, email VARCHAR(254) NULL, phone VARCHAR(40) NULL, notes TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS documents (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL,
  orig_name VARCHAR(200) NOT NULL, stored_name VARCHAR(120) NOT NULL,
  category VARCHAR(40) DEFAULT 'otro', mime VARCHAR(120), size INT,
  confidential TINYINT NOT NULL DEFAULT 1,
  visible_to_client TINYINT NOT NULL DEFAULT 0,
  uploaded_by INT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- Si la tabla ya existía sin la columna:
-- ALTER TABLE documents ADD COLUMN visible_to_client TINYINT NOT NULL DEFAULT 0 AFTER confidential;

CREATE TABLE IF NOT EXISTS findings (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL,
  title VARCHAR(200) NOT NULL, severity ENUM('alto','medio','bajo') NOT NULL DEFAULT 'medio',
  recommendation TEXT NULL, body TEXT NULL, created_by INT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS checklist_items (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL,
  label VARCHAR(200) NOT NULL, category VARCHAR(80) NULL, done TINYINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS requests (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL,
  item VARCHAR(255) NOT NULL, status ENUM('pedido','recibido','pendiente') NOT NULL DEFAULT 'pedido',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS time_entries (
  id INT AUTO_INCREMENT PRIMARY KEY, case_id INT NOT NULL, user_id INT NULL,
  work_date DATE NULL, minutes INT NOT NULL DEFAULT 0, rate DECIMAL(10,2) NOT NULL DEFAULT 0,
  billable TINYINT NOT NULL DEFAULT 1, invoiced TINYINT NOT NULL DEFAULT 0, note VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS conflicts (
  id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(200) NOT NULL, note TEXT NULL,
  created_by INT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY, ip VARCHAR(64), email VARCHAR(254),
  at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (email, at), INDEX (ip, at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
